trigger:
- master  # Assuming 'master' is your main branch, adjust as necessary

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    echo "Creating a basic requirements.txt"
    echo "pytest" > requirements.txt
  displayName: 'Create requirements.txt'

- script: |
    python -m venv env
    source env/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    source env/bin/activate
    pytest
  displayName: 'Run tests'
